/**
 * Tipos para o módulo de Planograma
 * Sistema de gestão visual de gôndolas para varejo alimentar
 */

// Tipos de planograma
export type PlanogramType = 'normal' | 'promocional' | 'sazonal' | 'evento';

// Status do planograma
export type PlanogramStatus = 'rascunho' | 'publicado' | 'em_revisao' | 'expirado' | 'arquivado';

// Status de execução/compliance
export type ComplianceStatus = 'pendente' | 'em_andamento' | 'concluido' | 'atrasado' | 'nao_conforme';

// Papéis específicos do planograma (além dos existentes)
export type PlanogramRole = 'merchandiser' | 'category_manager' | 'repositor';

/**
 * Estrutura de uma prateleira na gôndola
 */
export interface Shelf {
  id: string;
  level: number; // Nível da prateleira (1 = base, incrementa para cima)
  height: number; // Altura em cm
  depth: number; // Profundidade em cm
  width: number; // Largura em cm
  eyeLevel?: boolean; // Se está na altura dos olhos (otimização de vendas)
}

/**
 * Módulo de gôndola (seção da estrutura física)
 */
export interface GondolaModule {
  id: string;
  name: string;
  order: number; // Ordem no corredor
  width: number; // Largura total em cm
  height: number; // Altura total em cm
  depth: number; // Profundidade em cm
  shelves: Shelf[];
  corridor?: string; // Corredor/seção da loja
}

/**
 * Produto posicionado no planograma (slot)
 */
export interface PlanogramSlot {
  id: string;
  productId: string; // Referência ao produto/SKU
  productName?: string; // Cache do nome
  productImage?: string; // Cache da imagem
  ean?: string; // EAN do produto

  // Posicionamento
  moduleId: string; // Módulo da gôndola
  shelfId: string; // Prateleira
  column: number; // Coluna (posição horizontal)
  row: number; // Linha (se houver empilhamento)

  // Quantidade e espaço
  facings: number; // Número de frentes (faces visíveis)
  depth: number; // Profundidade em unidades
  totalUnits: number; // Total de unidades planejadas

  // Métricas
  priority?: number; // Prioridade de exposição (1-10)
  rotation?: 'horizontal' | 'vertical'; // Orientação do produto

  // Dados de negócio
  margin?: number; // Margem de lucro (%)
  salesVelocity?: number; // Velocidade de venda
  promoted?: boolean; // Se está em promoção
}

/**
 * Planograma Base (template aplicável a múltiplas lojas)
 */
export interface PlanogramBase {
  id: string;
  name: string;
  description: string;
  type: PlanogramType;

  // Organização
  companyId: string;
  category: string; // Categoria de produtos (bebidas, laticínios, etc.)
  subcategory?: string;

  // Estrutura física
  modules: GondolaModule[];

  // Produtos e posicionamento
  slots: PlanogramSlot[];

  // Metadata
  version: number;
  createdBy: string;
  createdByName?: string;
  createdAt: string;
  updatedAt: string;

  // Configurações
  estimatedDuration?: number; // Tempo estimado de execução (minutos)
  requiresPhoto?: boolean; // Se requer foto para compliance
  requiresSignature?: boolean; // Se requer assinatura

  // Status
  status: PlanogramStatus;

  // Métricas calculadas
  totalSKUs?: number;
  totalFacings?: number;
  spaceUtilization?: number; // % de espaço ocupado
}

/**
 * Ajustes específicos de loja
 */
export interface StoreAdjustment {
  type: 'add' | 'remove' | 'replace' | 'reorder';
  originalSlotId?: string; // Slot original (se aplicável)
  newSlot?: PlanogramSlot; // Novo slot
  reason?: string; // Motivo do ajuste
  autoGenerated?: boolean; // Se foi gerado automaticamente
}

/**
 * Planograma Store-Specific (adaptado para uma loja específica)
 */
export interface PlanogramStore {
  id: string;
  basePlanogramId: string;
  basePlanogramName?: string;

  // Loja específica
  storeId: string;
  storeName?: string;

  // Estrutura pode ser diferente da base
  modules: GondolaModule[];
  slots: PlanogramSlot[];

  // Ajustes aplicados
  adjustments: StoreAdjustment[];

  // Datas
  validFrom: string;
  validUntil?: string;
  publishedAt?: string;
  publishedBy?: string;

  // Status
  status: PlanogramStatus;

  // Metadata
  createdAt: string;
  updatedAt: string;

  // Flags
  autoGenerated?: boolean; // Se foi gerado automaticamente
  requiresReview?: boolean; // Se precisa revisão manual
}

/**
 * Detecção de problema pela IA
 */
export interface ComplianceIssue {
  type: 'missing_product' | 'wrong_position' | 'wrong_quantity' | 'gap' | 'foreign_product' | 'damaged' | 'expired';
  severity: 'low' | 'medium' | 'high' | 'critical';
  productId?: string;
  productName?: string;
  slotId?: string;
  expectedPosition?: { shelf: string; column: number };
  actualPosition?: { shelf: string; column: number };
  description: string;
  confidence?: number; // Confiança da IA (0-100)
}

/**
 * Resultado da análise de IA de uma foto
 */
export interface AIAnalysisResult {
  analysisId: string;
  timestamp: string;

  // Score geral
  complianceScore: number; // 0-100

  // Problemas detectados
  issues: ComplianceIssue[];

  // Estatísticas
  totalProducts: number;
  productsDetected: number;
  productsMissing: number;
  productsWrongPosition: number;
  gaps: number;

  // Metadata da análise
  provider?: 'rekognition' | 'vision' | 'azure' | 'mock';
  processingTime?: number; // ms
  confidence: number; // Confiança geral
}

/**
 * Tarefa de execução de planograma
 */
export interface ComplianceTask {
  id: string;
  planogramStoreId: string;
  planogramName?: string;

  // Loja e responsável
  storeId: string;
  storeName?: string;
  assignedTo?: string; // userId do repositor
  assignedToName?: string;

  // Detalhes da tarefa
  moduleId?: string; // Módulo específico ou planograma completo
  moduleName?: string;
  category?: string;

  // Datas
  scheduledDate: string;
  dueDate?: string;
  startedAt?: string;
  completedAt?: string;

  // Status
  status: ComplianceStatus;

  // Metadata
  createdAt: string;
  updatedAt: string;

  // Prioridade
  priority?: 'low' | 'medium' | 'high' | 'urgent';
}

/**
 * Execução de compliance (realograma)
 */
export interface ComplianceExecution {
  id: string;
  taskId: string;
  planogramStoreId: string;

  // Loja e usuário
  storeId: string;
  storeName?: string;
  executedBy: string;
  executedByName?: string;

  // Fotos capturadas
  photos: {
    id: string;
    url: string;
    moduleId?: string; // Módulo fotografado
    timestamp: string;
    gpsLocation?: {
      latitude: number;
      longitude: number;
    };
  }[];

  // Análise de IA
  aiAnalysis?: AIAnalysisResult;

  // Avaliação manual
  manualReview?: {
    score: number;
    notes: string;
    reviewedBy: string;
    reviewedAt: string;
  };

  // Conformidade geral
  complianceScore: number; // 0-100
  status: ComplianceStatus;

  // Ações corretivas
  correctiveActions?: {
    description: string;
    completedAt?: string;
    completedBy?: string;
  }[];

  // Datas
  executedAt: string;
  createdAt: string;
  updatedAt: string;

  // Notas
  notes?: string;
  signature?: string; // Base64 da assinatura (se requerida)
}

/**
 * Snapshot de estoque para planejamento
 */
export interface InventorySnapshot {
  id: string;
  storeId: string;
  productId: string;

  // Quantidades
  currentStock: number;
  minStock: number;
  maxStock: number;

  // Flags
  inStock: boolean;
  lowStock: boolean;
  overstock: boolean;

  // Metadata
  lastUpdated: string;
  source: 'manual' | 'csv' | 'api' | 'erp';
}

/**
 * KPIs de planograma
 */
export interface PlanogramKPIs {
  storeId?: string;
  storeName?: string;
  period: {
    start: string;
    end: string;
  };

  // Conformidade
  avgComplianceScore: number;
  executionsTotal: number;
  executionsOnTime: number;
  executionsLate: number;

  // Problemas
  totalIssues: number;
  criticalIssues: number;
  resolvedIssues: number;

  // Produtos
  avgProductsDetected: number;
  avgProductsMissing: number;
  avgGaps: number;

  // Performance
  bestStore?: string;
  worstStore?: string;
  topCategories?: { category: string; score: number }[];
}

/**
 * Calendário de promoções
 */
export interface PromotionCalendar {
  id: string;
  name: string;
  description: string;
  type: 'promocao' | 'evento' | 'sazonalidade';

  // Período
  startDate: string;
  endDate: string;

  // Lojas aplicáveis
  companyId: string;
  storeIds: string[];

  // Planograma associado
  planogramBaseId?: string;
  planogramBaseName?: string;

  // Produtos em promoção
  promotedProducts?: {
    productId: string;
    productName?: string;
    discountPercent?: number;
    highlightColor?: string;
  }[];

  // Status
  active: boolean;

  // Metadata
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}
